---
title: "IML week 6"
output: html_notebook
---

1 a
```{r}
load_mnist <- function() {
  load_image_file <- function(filename) {
    ret = list()
    f = file(filename,'rb')
    readBin(f,'integer',n=1,size=4,endian='big')
    ret$n = readBin(f,'integer',n=1,size=4,endian='big')
    nrow = readBin(f,'integer',n=1,size=4,endian='big')
    ncol = readBin(f,'integer',n=1,size=4,endian='big')
    x = readBin(f,'integer',n=ret$n*nrow*ncol,size=1,signed=F)
    ret$x = matrix(x, ncol=nrow*ncol, byrow=T)
    close(f)
    ret
  }
  load_label_file <- function(filename) {
    f = file(filename,'rb')
    readBin(f,'integer',n=1,size=4,endian='big')
    n = readBin(f,'integer',n=1,size=4,endian='big')
    y = readBin(f,'integer',n=n,size=1,signed=F)
    close(f)
    y
  }
  train <<- load_image_file('mnist/train-images-idx3-ubyte')
  test <<- load_image_file('mnist/t10k-images-idx3-ubyte')
  
  train$y <<- load_label_file('mnist/train-labels-idx1-ubyte')
  test$y <<- load_label_file('mnist/t10k-labels-idx1-ubyte')  
}

show_digit <- function(arr784, col=gray(12:1/12), ...) {
  image(matrix(arr784, nrow=28)[,28:1], col=col, ...)
}

library(proxy)
load_mnist()

training <- as.matrix(train$x)
training <- training[1:5000,1:784]
testing <- as.matrix(test$x)
testing <- testing[1:1000, 1:784]

distances <- dist(training, testing)
print(distances[1,1])
```

1 b
```{r}

training_classes <- train$y[1:5000]
test_classes <- test$y[1:1000]

knn <- function(training, training_classes, distances, k){
  print(k)
  results <- vector()
  
  for(i in 1:ncol(distances)){
    neighbours <- vector()
    possible_neighbours <- distances[,i]
    
    #find k actual nearest neighbors
    for(j in 1:k){
      minimum_index <- which.min(possible_neighbours)
      neighbours <- rbind(neighbours, training_classes[minimum_index])
      possible_neighbours[minimum_index] <- NA
    }
    
    # find the most common class and store the result
    results[i] <- names(sort(table(neighbours), decreasing=TRUE))[1]
  }
  
  return(results)
}


errors <- vector()
for(k in 1:50){
  res <- knn(training, training_classes, distances, k)
  errors <- c(errors, 1-sum(test_classes == res)/1000)
}

plot(1:50, errors, type="l")

```



